CREATE TABLE `ADDRESS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CITY` varchar(20) DEFAULT NULL,
  `ZIP_CODE` varchar(10) DEFAULT NULL,
  `STREET_NAME` varchar(20) DEFAULT NULL,
  `STREET_NUMBER` varchar(20) DEFAULT NULL,
  `TMSTP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  `IDENTIFICATION_NUMBER` varchar(10) NOT NULL,
  `TMSTP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PIN_IX_UQ` (`IDENTIFICATION_NUMBER`)
) ENGINE=InnoDB;

CREATE TABLE `USER_ADDRESS` (
  `USER_ID` bigint(20) NOT NULL,
  `ADDRESS_ID` bigint(20) NOT NULL,
  `TMSTP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`,`ADDRESS_ID`),
  KEY `ADDRESS_ID_FK` (`ADDRESS_ID`),
  CONSTRAINT `ADDRESS_ID_FK` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `ADDRESS` (`ID`),
  CONSTRAINT `USER_ID_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB;